### ISSUE TITLE
New Workflow: Keep date and time on the property (multiple value)

### ISSUE THREAD

**Issue by YU000jp** [YU000jp/logseq-plugin-confirmation-done-task#22]
### Discussed in https://github.com/YU000jp/logseq-plugin-confirmation-done-task/discussions/9

<div type='discussions-op-text'>

<sup>Originally posted by **yoghurtdewdew** June 25, 2023</sup>
When I click on checkbox to cancel done and then redo done, property added will not update. I would prefer to add another new date&time property while keep the previous done date&time property, so that I can see different completion dates&time properies for review them.</div>

**Comment by YU000jp** [comment]
![DONEblockMenuItem](https://github.com/YU000jp/logseq-plugin-confirmation-done-task/assets/111847207/56857d1b-8b30-40f1-9d15-97e32f927bc0)

**Comment by ransheng11** [comment]
Thank you very much for your work. I just started using Logseq. I downloaded two versions, 1.14 and 1.16. When I turn on both of them, I can't use multiple attributes. 
![20241020163945](https://github.com/user-attachments/assets/fb4b23f3-470e-4ad5-99a4-e813c83cb035)
