### ISSUE TITLE
Date recorded is 24 hours earlier than input

### ISSUE THREAD

**Issue by 64bakerst** [YU000jp/logseq-plugin-confirmation-done-task#32]
Example: Move task to DONE - completion popup shows up, double check the date to eg. 08/13/2023. The value in the completion parameter gets set to 08/12/2023. Same time - just one day earlier. 

On Linux (Zorin).

**Comment by YU000jp** [comment]
It is a bug. We've released a new update. The condition for this bug seems to be when the time zone is at least 1 hour behind UTC.
