### ISSUE TITLE
Remove the `completed` property when the task moves from `DONE` back to `TODO`

### ISSUE THREAD

**Issue by andreoliwa** [YU000jp/logseq-plugin-confirmation-done-task#34]
First of all, thanks for this plugin. 🙏🏻

I come from [logseq-plugin-task-check-date](https://github.com/DimitryDushkin/logseq-plugin-task-check-date) and I miss one feature: clearing the `completed` property when I undo a task.

This could be a setting so people can choose the behaviour they prefer.

I saw https://github.com/YU000jp/logseq-plugin-confirmation-done-task/issues/22 but the "Add to DONE" menu option doesn't fit my workflow.

**Comment by YU000jp** [comment]
Shortcut `Ctrl + Z` allows to "redo".
Or does it mean that you want to get rid of the property later?

The workflow is an option to have multiple values.

**Comment by andreoliwa** [comment]
> Or does it mean that you want to get rid of the property later?

When a task is `DONE` and I click on it again, it returns to `TODO`.
But the `completed` property is still there.

I would like it deleted when a task becomes `TODO` again.


https://github.com/YU000jp/logseq-plugin-confirmation-done-task/assets/1258218/9a01c0cd-e1fa-4c08-98fa-d7e464a09da2

**Comment by YU000jp** [comment]
I see. Release it.
