### ISSUE TITLE
Omit date if task is on journal page and completed same date

### ISSUE THREAD

**Issue by willettjf** [YU000jp/logseq-plugin-confirmation-done-task#43]
If the task is on a journal page, and it is completed the same day (completed date matches journal page date), then omit the date.

**Comment by YU000jp** [comment]
It's possible. Make it one option.

**Comment by YU000jp** [comment]
https://github.com/YU000jp/logseq-plugin-confirmation-done-task/issues/44#issuecomment-1778584352
Included in new version. This change is now turned off by default. Please turn it on.

- Plugin Settings
  1. Date > Omit date if same as journal
     > default: `false`
