### ISSUE TITLE
Option to append time and date to (1) end of block and (2) different order 

### ISSUE THREAD

**Issue by willettjf** [YU000jp/logseq-plugin-confirmation-done-task#44]
Instead of:
DONE [[Oct 23rd, 2023]] **14:41** - Share schedule with students

This:
DONE Share schedule with students - **14:41** [[Oct 23rd, 2023]]

Related to [issue 43](https://github.com/YU000jp/logseq-plugin-confirmation-done-task/issues/43):
By putting date at the end of the block, it will be consistent in either case.

On non-journal page: DONE Share schedule with students - **14:41** [[Oct 23rd, 2023]]
On journal page: DONE Share schedule with students - **14:41**

**Comment by YU000jp** [comment]
It's possible. Make it two option.
1. end of block
1. different order (time and date)

**Comment by YU000jp** [comment]
I released a new version. These changes are now turned off by default. Please turn it on.

- Plugin Settings
  1. Time > Different order (time and date)
     > default: `after`
  1. Mode > "Update block" > Before or after the content of the first line, insert the date and time
     > default: `before`
