### ISSUE TITLE
Pop-up to select completion date doesn't show on a task with child nodes

### ISSUE THREAD

**Issue by andreoliwa** [YU000jp/logseq-plugin-confirmation-done-task#46]
👋🏻 Hi! Here are the steps to reproduce:

1. Add a bullet `TODO Parent`
2. Add a child bullet `Child`
3. Complete the `TODO Parent`
4. It becomes `DONE Parent` but no pop-up to select dates appear

I have the latest version [v.11.0](https://github.com/YU000jp/logseq-plugin-confirmation-done-task/releases/tag/v1.11.0).

My settings from `~/.logseq/settings/logseq-plugin-confirmation-done-task.json`:
```json
{
  "addDate": true,
  "createDateLink": true,
  "omitDateIfSameAsJournal": true,
  "addTime": false,
  "timeStampPosition": "after",
  "emphasisTime": "*",
  "smallDONEproperty": true,
  "onlyFromBulletList": false,
  "removePropertyWithoutDONEtask": true,
  "enableHiddenProperty": true,
  "updateBlockContentPosition": "before",
  "updateBlockSeparator": " - ",
  "insertBlockCollapsed": false,
  "modeSelect": "As block property",
  "timeoutMode": true,
  "timeout": "5000",
  "customPropertyName": "completed",
  "disabled": false,
  "insertBlockModeUseReference": true
}
```

Here's a screen recording:

https://github.com/YU000jp/logseq-plugin-confirmation-done-task/assets/1258218/8b9605e7-daa6-4fb2-a31a-15f3d45eb230

**Comment by YU000jp** [comment]
I see. When I looked into it now, it was a bug. The condition is when the task becomes DONE again.
Thank you for posting the details. 🫡

**Comment by YU000jp** [comment]
I released a new version. Please update.

**Comment by andreoliwa** [comment]
It works, thank you! 🙏🏻
