### ISSUE TITLE
The query does not work

### ISSUE THREAD

**Issue by moneyThanks** [YU000jp/logseq-plugin-confirmation-done-task#53]
I found that as long as I change the title of the task, adding some text, it can be queried. If there is no change in the task-related information, it cannot be queried. I wrote a query statement for tasks from 7 days ago, which should be able to find 4 tasks. At first, none could be found. I changed the titles of two tasks, and these two tasks were both retrieved. Without changes, they cannot be found.
![image](https://github.com/YU000jp/logseq-plugin-confirmation-done-task/assets/53850878/ae3d5cb2-b57d-4c34-8101-e6a49c3ab090)
![image](https://github.com/YU000jp/logseq-plugin-confirmation-done-task/assets/53850878/c1a510bc-0e58-4402-98b4-9c31125c6931)
![image](https://github.com/YU000jp/logseq-plugin-confirmation-done-task/assets/53850878/0457d393-551c-4976-bb8c-1abf51eca749)

**Comment by YU000jp** [comment]
I released a new version. Please try it.
