### ISSUE TITLE
Feature request: Completion info on same line possible?

### ISSUE THREAD

**Issue by hoegge** [YU000jp/logseq-plugin-confirmation-done-task#57]
If possible, it would be great if there was an option to put the completion info on same line instead of taking up a new line.
I realize it might limit the formatting feature, but would be nice to keep things on one line in a longer list.

And thanks for plugin

**Comment by YU000jp** [comment]
I will consider it. Could you rearrange the strings and make a screenshot? I do not have a notation idea yet.

**Comment by hoegge** [comment]
Current layout:
![image](https://github.com/user-attachments/assets/6c152f37-a7d0-41c9-803c-6003840bdc8b)
Suggestion:
![image](https://github.com/user-attachments/assets/0c9776eb-5293-41aa-8253-4ce729ae60bc)
where I just removed the return at the end but could be good if the "Tag" was shown too and right aligned like this (but I don't know LogSeq enough to do that - so just a painted result):
![image](https://github.com/user-attachments/assets/ec3423eb-f787-49ab-94b1-d9bd0acb7060)

**Comment by YU000jp** [comment]
I will try and release a style option that puts the completed property one level higher.

**Comment by YU000jp** [comment]
I released a new version. Please update. This change is switched off by default. A toggle has been added as a new item in the plugin settings. Problems may arise depending on the block text and its combination with the preceding and following blocks. Please let me know if this is the case.
![image](https://github.com/user-attachments/assets/23673e5c-e6f2-462d-9e08-bb24ba8d60a3)

**Comment by hoegge** [comment]
Great - much better - great improvement - not exactly on same line but maybe not possible. But much better. Thanks a lot!
